name = "playora-realtime"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurableObject" },
  { name = "MATCHMAKING_DO", class_name = "MatchmakingDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[observability]
enabled = true

[[migrations]]
tag = "v2"
new_sqlite_classes = ["MatchmakingDurableObject"]
